#! /bin/bash
# Conditional debugging API
#
# How to use:
#   _debug_on sshagent
# then later in the code
#   _debug sshagent FOO THE BAR
# where "FOO THE BAR" will be printed to stdout if debugging is turned on
# for sshagent.

# Need BASH 4 for "declare -A".
if [ ${BASH_VERSINFO[0]} -lt 4 ]; then
    # define dummy versions of the API
    function _debug_on { return 0; }
    function _debug_off { return 0; }
    function _debug { return 0; }
    # always return false, since debugging is never `on' in this case
    function _debug_p { return 1; }
    return 0
fi

declare -A __my_debug

# Turn debugging on for $1
function _debug_on {
    __my_debug[$1]=nonnull
}

# Turn debugging off for $1
function _debug_off {
    __my_debug[$1]=
}

# Output debugging info for $1. Args 2 through n are echo'd to stderr.
function _debug {
    local thing=$1
    shift

    if [ "${__my_debug[$thing]-}" ]; then
	echo "$@" 1>&2
    fi
    return 0
}

# Return true if debugging is turned on for $1
function _debug_p {
    local thing=$1

    if [ "${__my_debug[$thing]-}" ]; then
	return 0
    else
	return 1
    fi
}

