#! /usr/bin/env zsh
# Use zsh because the native BASH on macOS is too old to
# run this script.

set -eu
set -o pipefail

### this was needed on macdev?
export PATH=/usr/local/bin:$PATH

prog="$(basename "$0")"

function usage {
    [ "${*-}" ] && echo "$prog: $*" 1>&2
    cat 1>&2 <<EOF
Usage: $prog [--clean]
Usage: $prog --list
Usage: $prog --dry-run
Usage: $prog --orphans
Usage: $prog --oob

Install Homebrew packages.

--list is used to list the would-be-installed packages.

--dry-run is used to see what would actually be installed, given
the already-installed packages on the current system.

--orphans is used to find packages installed for a dependency but their
original package was removed.

--oob is used to see what packages were installed outside of this script,
so they might be added to it.

Options:
--clean   :: clean up after installation

Consider using these commands to gain more insight into installed packages:

  \$ brew deps --tree --installed

  \$ brew uses --installed protobuf

EOF
    exit 1
}

function errordie {
    [ "${*-}" ] && echo "$prog: $*" 1>&2
    exit 1
}

brew=$(whence -p brew) > /dev/null || errordie Homebrew is not installed

function d {
    echo "+ $*"
    "$@"
}

packages_with_options=()

host=$(hostname -s)

if id -Gn "$USER" | grep -q -w admin; then
    manager=($brew)
elif [ -f "$HOME/.ssh/id_rsa_nopw" ]; then
    manager=(ssh -i $HOME/.ssh/id_rsa_nopw admin@$host ${brew})
else # assume SSH works to admin@...
    manager=(ssh admin@$host ${brew})
fi

# You can see what you have installed via these commands:
#   brew leaves --installed-on-request
#   brew ls --casks

packages=(
    # needed by mount_smb, which I don't really use anymore
    #autossh

    bash coreutils curl diffutils dos2unix duti findutils
    findutils gcc git gnu-getopt gnu-sed gnu-tar grep jq ijq lsof moreutils
    ncdu openssh p7zip lzip perl python rsync shellcheck smartmontools
    sqlite telnet wget xmlstarlet zlib the-unarchiver gnu-units
    pkgconf openssl@3

    # Use native rclone from https://rclone.org/downloads/, it has more
    # features.
#   rclone

    # file encryption
    age

    # for knocking:
    fwknop
    1password-cli

    # like inotifywait
    fswatch

    # cool commands to learn about other commands
    # "tldr" was deprecated
    cheat

    # the screen with macOS sucks
    screen

    # procmail is for lockfile
    procmail

    # mailx-like package
    s-nail

    # Needed for SOC 2
    clamav

    # for M-x ispell
    ispell

    # `watch progress -q` is a nice way to watch the bandwidth used
    # by `cp`.
    progress watch

    # these are for building packages from source (e.g., fwknop)
    make awk autogen autoconf automake texinfo

    # different than 'awk'
    gawk

#####TODO:
    # not sure these are needed
    libev
    openjdk

##### can probably remove:
    wakeonlan

    # USB thumb driver creator
    #balenaetcher

    # requires the emacs-plus tap below
    #emacs-plus-app
)

taps=(
    #"emacs-plus:d12frosted/emacs-plus"
)

pipx_packages=()

if [[ $host =~ ^(max|mini18|mini24) ]]; then
    packages+=(
        yt-dlp
    )
fi

if [[ $host =~ ^(max) ]]; then

    packages+=(
        # This still works!
        apcupsd

        # photography tools used by various scripts
        imagemagick exiftool

        # audio editor
        audacity

        # used to convert org/markdown files to PDFs
        mactex pandoc

        ###### I PURCHASED BOTH OF THESE
        # https://tclementdev.com/timemachineeditor/
        timemachineeditor
        # https://www.soma-zone.com/BackupLoupe/
        backuploupe

        # for Fujitsu ix500 scanner
        homebrew/cask/fujitsu-scansnap-home

        # for osxphotos (see below)
        pipx

        # ebook reader
        calibre

        # see below for install with options, but I don't really need that??
        ffmpeg
        handbrake-app

        # for emacs ready-player
        ffmpegthumbnailer

        # used to chop up videos (e.g., Adrian's graduation video!)
        losslesscut

        # used by bink/diffdocx
        diff-pdf

        # for photos and tget
        sqlite-utils
        sqldiff

        # useful for archiving iMessage data
        imessage-exporter 

        # OCaml package manager... `opam list --installed` to see what is
        # there.  I don't remember installing any of that stuff.
        opam

        # rival CL!!
        sbcl

        # default browser so I can redirect URLs to specific browsers
        finicky

        # manipulate google calendar
        gcalcli

        # testing this out, for markdown editing, etc
        obsidian

        # protection apps
        knockknock
        blockblock
        #reikey

        # testing these
        dockutil media-control qemu usage gh sox
        ical-buddy mole

        # listed to quiet runs with --oob arg
        protobuf
    )

    pipx_packages+=(
        # https://rhettbull.github.io/osxphotos/
        ###osxphotos
    )
fi

##### too big and I don't really use it much
#if [[ $host =~ (max|mini18) ]]; then
#    # ffmpeg with improved AAC codec
#    packages_with_options+=("homebrew-ffmpeg/ffmpeg/ffmpeg --with-fdk-aac")
#fi

###############################################################################

orphans=
clean=
list=
dryrun=
oob=

while [ $# -gt 0 ]; do
    case $1 in
        --help)    usage ;;
        --orphans) orphans=$1 ;;
        --clean)   clean=$1 ;;
        --list)    list=$1 ;;
        --dry-run) dryrun=$1 ;;
        --oob)     oob=$1 ;;
        *)         break ;;
    esac
    shift
done

function member {
    local item=$1
    shift

    while test $# -gt 0; do
	if [ "$item" = "$1" ]; then
	    return 0
	fi
	shift
    done

    return 1
}

if [ "$list" ]; then
    for p in "${packages[@]}"; do echo $p; done
    for p in "${packages_with_options[@]}"; do echo $p; done
    exit 0
elif [ "$orphans" ]; then
    for leaf in $(brew leaves --installed-as-dependency); do
        if ! member "$leaf" "${packages[@]}"; then
            echo "$leaf"
        fi
    done
    exit 0
elif [ "$oob" ]; then
    # print things not in "${packages[@]}" but that
    # `brew list --installed-on-request` prints
    depends=( ${(f)"$(brew list --installed-as-dependency)"} )
    for p in $(brew list --installed-on-request); do
        if ! member "$p" "${packages[@]}"; then
            if ! member "$p" "${depends[@]}"; then
                echo "installed outside of script: $p"
            fi
        fi
    done
    exit 0
fi

{
    d "${manager[@]}" analytics off
    d "${manager[@]}" update

    if [ "${#taps[@]}" -gt 0 ]; then
        for tap in "${taps[@]}"; do
            if [[ $tap =~ ^(.*):(.*)$ ]]; then
                name="${match[1]}"
                path="${match[2]}"
            else
                errordie "Could not parse tap: $tap"
            fi
            if ! d "${manager[@]}" list "$name"; then
                echo "Tapping $name..."
                d "${manager[@]}" tap "$path"
                d "${manager[@]}" install $dryrun "$name"
            else
                echo "Tap $name already installed."
            fi
        done
    fi

    d "${manager[@]}" upgrade $dryrun

    d "${manager[@]}" install $dryrun "${packages[@]}"
    for package_with_options in "${packages_with_options[@]}"; do
        d "${manager[@]}" install $dryrun $package_with_options
    done

    [ "${#pipx_packages[@]}" -gt 0 ] &&
        d pipx install $dryrun "${pipx_packages[@]}"

    [ "$clean" ] && d "${manager[@]}" cleanup
    exit 0
}
