#! /usr/bin/env bash

set -eu

SCRIPTDIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

host=$(hostname -s)
function d {
    if id -Gn "$USER" | grep -q -w admin; then
        echo "+ $*"
        "$@"
    else
        echo "+ ssh admin@$host $*"
        ssh "admin@$host" "$@"
    fi
}

if ! brew=$(type -p brew); then
     errordie brew is not installed or in PATH
fi

{
    d "$brew" update
    # This specifically does NOT upgrade casks.  So, it doesn't upgrade
    # alt-tab, for example.  That program does auto-updating.
    # To upgrade casks, a separate command is needed, see below.
    d "$brew" upgrade
    #d "$brew" upgrade --cask
    d "$brew" cleanup
    if ! d "$brew" doctor; then
        echo "Warning: doctor return a non-zero status"
    fi
    set -x
    $SCRIPTDIR/brew_symlinks --exec
    exit 0
}
