#! /usr/bin/env bash

set -eu -o pipefail

host=$(hostname -s)

prog="$(basename "$0")"
SCRIPTDIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

function errordie {
    [ "${*-}" ] && echo "$prog: $*" 1>&2
    exit 1
}

function d {
    if id -Gn "$USER" | grep -q -w admin; then
        echo "+ $*"
        "$@"
    else
        echo "+ ssh admin@$host $*"
        # shellcheck disable=SC2029
        ssh "admin@$host" "$@"
    fi
}

if ! brew=$(type -p brew); then
     errordie brew is not installed or in PATH
fi

{
    d "$brew" update
    d "$brew" upgrade
    d "$brew" cleanup --prune=all
    if ! d "$brew" doctor; then
        echo "Warning: doctor return a non-zero status"
    fi
    d "$SCRIPTDIR/brew_symlinks" --exec
    exit 0
}
