#! /usr/bin/env zsh
# Use zsh because the native BASH on macOS is too old to
# run this script.

set -eu
set -o pipefail

prog="$(basename "$0")"

function usage {
    [ "${*-}" ] && echo "$prog: $*" 1>&2
    cat 1>&2 <<EOF
Usage: $prog [--clean]
Usage: $prog --list

Install Homebrew packages.  To list packages 
use --list.

Options:
--clean   :: clean up after installation
EOF
    exit 1
}

function errordie {
    [ "${*-}" ] && echo "$prog: $*" 1>&2
    exit 1
}

type -p brew > /dev/null || errordie Homebrew is not installed

function d {
    echo "+ $*"
    "$@"
}

packages_with_options=()

host=$(hostname -s)

brew="brew"
if id -Gn "$USER" | grep -q -w admin; then
    manager=$brew
elif [ -f "$HOME/.ssh/id_rsa_nopw" ]; then
    manager=(ssh -i $HOME/.ssh/id_rsa_nopw admin@$host ${brew})
else # assume SSH works to admin@...
    manager=(ssh admin@$host ${brew})
fi

packages=(
    autossh bash coreutils curl diffutils findutils
    git grep jq moreutils findutils openssh wget

    # for knocking:
    #fwknop ...... now installed from source code
    1password-cli

    gnu-sed gnu-tar perl xmlstarlet shellcheck
    python rsync lsof p7zip 
    ncdu telnet rclone duti gnu-getopt
    sqlite sqldiff smartmontools
    # too useful, but oy vey, the security implications!
    node npm

    # like inotifywait
    fswatch

    # cool commands to learn about other commands
    cheat tldr

    # the screen with macOS sucks
    screen
    # procmail is for lockfile
    procmail

    # mailx-like package
    s-nail

    # Needed for SOC 2
    clamav

    # for M-x ispell
    ispell

    # `watch progress -q` is a nice way to watch the bandwidth used
    # by `cp`.
    progress watch

    # these are for building packages from source (e.g., fwknop)
    autogen autoconf automake texinfo
)

pipx_packages=()

npm_packages=()

if [[ $host =~ (max) ]]; then
    # "imagemagick" and "exiftool" are photography tools used
    #   by various scripts
    # "basictex" is for the program "pdflatex" used by...
    # "pandoc" to convert markdown to PDF files
    packages+=(
        imagemagick exiftool basictex pandoc
        # https://tclementdev.com/timemachineeditor/
        timemachineeditor

        # for Fujitsu ix500 scanner
        homebrew/cask/fujitsu-scansnap-home

        # https://alt-tab-macos.netlify.app/
        #### don't use this anymore
        #alt-tab

        # for osxphotos (see below)
        pipx

        # ebook reader
        calibre
    )
    npm_packages+=(
        # https://github.com/sindresorhus/one-thing CLI for the One Thing app
        one-thing
    )

    pipx_packages+=(
        # https://rhettbull.github.io/osxphotos/
        osxphotos
    )
fi

##### too big and I don't really use it much
#if [[ $host =~ (max|mini18) ]]; then
#    # ffmpeg with improved AAC codec
#    packages_with_options+=("homebrew-ffmpeg/ffmpeg/ffmpeg --with-fdk-aac")
#fi

###############################################################################

clean=
list=

while [ $# -gt 0 ]; do
    case $1 in
        --help)  usage ;;
        --clean) clean=$1 ;;
        --list)  list=$1 ;;
        *)       break ;;
    esac
    shift
done

if [ "$list" ]; then
    for p in "${packages[@]}"; do echo $p; done
    for p in "${packages_with_options[@]}"; do echo $p; done
    exit 0
fi

{
    d "${manager[@]}" analytics off
    d "${manager[@]}" update
    d "${manager[@]}" upgrade

    d "${manager[@]}" install "${packages[@]}"
    for package_with_options in "${packages_with_options[@]}"; do
        d "${manager[@]}" install $package_with_options
    done

    [ "${#npm_packages[@]}" -gt 0 ] && d npm install -g "${npm_packages[@]}"
    [ "${#pipx_packages[@]}" -gt 0 ] && d pipx install "${pipx_packages[@]}"

    [ "$clean" ] && d "${manager[@]}" cleanup
    exit 0
}
