#! /bin/bash

lsargs=

while test $# -gt 0; do
    case $1 in
	-r) lsargs="$lsargs -R" ;; 
	-*) lsargs="$lsargs $1" ;;
	*)  break
	    ;;
    esac
    shift
done

# shellcheck disable=SC2164,SC2086
diff <(cd "$1"; ls $lsargs -1 .) <(cd "$2"; ls $lsargs -1 .)
