#! /usr/bin/env bash

# https://github.com/d12frosted/homebrew-emacs-plus
# $ brew tap d12frosted/emacs-plus
# $ brew install emacs-plus-app
nohup "/Applications/Emacs.app/Contents/MacOS/Emacs" --debug-init "$@" &> /dev/null &
