#! /usr/bin/env bash

# https://github.com/d12frosted/homebrew-emacs-plus
# $ brew tap d12frosted/emacs-plus
# $ brew install emacs-plus
nohup "$(brew --prefix emacs-plus)/Emacs.app/Contents/MacOS/Emacs" --debug-init "$@" &> /dev/null &

exit 0

# On macOS 15 and Emacs 29.4, this became really, really sluggish and it
# was too annoying to use.  I used this version for so long.
# RIP emacsformacosx.com  :(
nohup /Applications/Emacs.app/Contents/MacOS/Emacs --debug-init "$@" &> /dev/null &
