#! /bin/bash
# Automate change various Mac OS X settings.
# It can be run any number of times and it will tell you what it changes,
# in case settings get reverted.

set -eu

function errordie {
    echo "Error: $*" 1>&2
    exit 1
}

restart_finder=

# Like "defaults write ..." but prints first arg to STDOUT if a
# change is made, nothing otherwise.
function d {
    local description="$1"; shift
    local domain="$1";      shift
    local key="$1";         shift

    local current
    local old
    local value
    local changed

    # $* is the value, which can be a single value or a pair:
    #   -string string_value
    #   -bool[ean] (true | false | yes | no)
    #   -int[eger] <integer_value>
    # we punt on all others

    write="echo $description"
    write="$write; defaults write \"$domain\" \"$key\" $@"

    if current=$(defaults read "$domain" "$key" 2>/dev/null); then
	# value for key exists, see if it's the same as what we want
	# it to be
	if [ $# -eq 1 ]; then
	    # simple case of a single value
	    if [ "$current" = "$1" ]; then
		: # Nothing to do
	    else
		old=$current
		eval "$write"
		echo "   ****** old value was: $old"
		changed=yes
	    fi
	else
	    case "$1" in
		-bool|-boolean)
		    case $2 in
			true|yes) value=1 ;;
			false|no) value=0 ;;
			*) errordie bad -boolean value: $2 ;;
		    esac
		    ;;
		-string)        value="$2" ;;
		-int|-integer)  value="$2" ;;
		*)  errordie $1 is unrecognized value ;;
	    esac
	    if [ "$current" = "$value" ]; then
		: # Nothing to do
	    else
		old=$current
		eval "$write"
		echo "   ****** old value was: $old"
		changed=yes
	    fi
	fi
    else
	# didn't exist, write it
	eval "$write"
	echo "   NEW SETTING"
	changed=yes
    fi
    
    if [ "$domain" = "com.apple.finder" ] && [ "$changed" ]; then
	restart_finder=xxx
    fi

}

d "Suppress Apple Photos from start on hotplug of cameras" \
  com.apple.ImageCapture disableHotPlug -bool true

d "Suppress xterm when X11 starts" org.x.X11 app_to_run $(which true)

d "Always show tab bar in Terminal" com.Apple.Terminal ShowTabBar 1

d "Setting screenshot location to $HOME/Downloads" \
  com.apple.screencapture location -string "$HOME/Downloads"

d "Setting screenshot format to PNG" \
  com.apple.screencapture type -string "png"

d "Disable shadow in screenshots" \
  com.apple.screencapture disable-shadow -bool true

d "Enable subpixel font rendering on non-Apple LCDs" \
  NSGlobalDomain AppleFontSmoothing -int 2

d "Automatically quit printer app once the print jobs complete" \
  com.apple.print.PrintingPrefs "Quit When Finished" -bool true

d "Ask for password when wake from sleep/screensaver" \
  com.apple.screensaver askForPassword -int 1

d "Password delay to 6 seconds" \
  com.apple.screensaver askForPasswordDelay -int 60

############## Finder...

d "Use list view in all Finder windows" \
  com.apple.finder FXPreferredViewStyle Nlsv

d "Do NOT show icons for hard drives, servers, etc on the desktop" \
  com.apple.finder ShowExternalHardDrivesOnDesktop -bool false

d "Show status bar in Finder" com.apple.finder ShowStatusBar -bool true
d "Show path bar in Finder"   com.apple.finder ShowPathbar -bool true

d "Display full POSIX path as Finder window title" \
  com.apple.finder _FXShowPosixPathInTitle -bool true

d "Disable the warning when changing a file extension" \
  com.apple.finder FXEnableExtensionChangeWarning -bool false

d "Disable window animations and Get Info animations" \
  com.apple.finder DisableAllAnimations -bool true

# Set Applications as the default location for new Finder windows
d "New Finder windows start in /Applications" \
  com.apple.finder NewWindowTargetPath -string "file:///Applications/"

d "Do not show recent tags" com.apple.finder ShowRecentTags -bool false

# Too annoying
d "Do NOT show hidden files" com.apple.finder AppleShowAllFiles -bool false

# So hidden files here:
chflags nohidden ~/Library

# For other paths, use `PfLo` and `file:///full/path/here/`
#defaults write com.apple.finder NewWindowTarget -string "PfLo"

d "Show all filename extensions in Finder" \
  NSGlobalDomain AppleShowAllExtensions -bool true

# Enable spring loading for directories
#defaults write NSGlobalDomain com.apple.springing.enabled -bool true
# Remove the spring loading delay for directories
#defaults write NSGlobalDomain com.apple.springing.delay -float 0

d "Avoid the creation of .DS_Store files on network volumes" \
  com.apple.desktopservices DSDontWriteNetworkStores -bool true

d "Disable the warning before emptying the Trash" \
  com.apple.finder WarnOnEmptyTrash -bool false

# Show the ~/Library folder for me
[ "$USER" = "layer" ] && chflags nohidden ~/Library

############## ...Finder

d "Minimize windows into their app icon" \
  com.apple.dock minimize-to-application -bool true

d "Show indicator lights for open applications in the Dock" \
  com.apple.dock show-process-indicators -bool true

d "No animation opening applications from the Dock" \
  com.apple.dock launchanim -bool false

d "Lower-left hot corner: sleep display" \
  com.apple.dock wvous-bl-corner -int 10
d "Lower-left hot corner: sleep display, part 2" \
  com.apple.dock wvous-bl-modifier -int 0

d "Prevent TM from prompting to use new drives as backup volumes" \
  com.apple.TimeMachine DoNotOfferNewDisksForBackup -bool true

# Assuming this won't hurt on non-laptops
d "Turn off keyboard illumination when not used for 5 minutes" \
  com.apple.BezelServices kDimTime -int 300

d "InitialKeyRepeat" NSGlobalDomain InitialKeyRepeat -int 35
d "KeyRepeat" NSGlobalDomain KeyRepeat -int 2

d "Terminal: copy attributes from Basic profile" \
  com.apple.Terminal CopyAttributesProfile Basic

d "Disable iCloud save default" \
  NSGlobalDomain NSDocumentSaveNewDocumentsToCloud -bool false

d "Disable smart quotes" \
  NSGlobalDomain NSAutomaticQuoteSubstitutionEnabled -bool false

d "Disable smart dashes" \
  NSGlobalDomain NSAutomaticDashSubstitutionEnabled -bool false

d "Enable the debug menu in Disk Utility" \
  com.apple.DiskUtility DUDebugMenuEnabled -bool true
d "Enable the advanced image options in Disk Utility" \
  com.apple.DiskUtility advanced-image-options -bool true

d "Enable Debug Menu in the Mac App Store" \
  com.apple.appstore ShowDebugMenu -bool true

d "Chrome: Use the system-native print preview dialog" \
  com.google.Chrome DisablePrintPreview -bool true
[ "$restart_finder" ] && killall Finder

# Because the macOS version is old
sudo port install openssh

# autossh for mount_smb
# git because it has security fixes over the Apple one
# coreutils because ... something needed for scripting?
# fwknop-client because I need to knock
# wget because it's handy
sudo port install autossh bash coreutils git fwknop-client wget

## don't install unless really necessary, since it pulls
## in a LOT of stuff and takes forever.
#sudo port install wireshark

# needed by disktest.sh, generally a better sed, since
# it has the -r flag (extended regex's)
sudo port install gsed

# because the built-in versions are insecure:
sudo port install openssl curl

# https://github.com/koalaman/shellcheck
sudo port install shellcheck

# This should be the default on Mac OS X.  It prevents all processes
# from getting sudo privs.
if ! sudo grep tty_tickets /etc/sudoers > /dev/null; then
    cat<<EOF
NOTE: add "Defaults tty_tickets" to /etc/sudoers
EOF
fi

shell="$(dscl . -read /Users/$USER UserShell)"
if [ "$shell" != "UserShell: /opt/local/bin/bash" ]; then
    cat <<EOF 
SHELL=$SHELL and not /opt/local/bin/bash.
Change it in System Preferences, Users & Groups, right-click on user and
select "Advanced Options..."
EOF
fi

# Disable captive portal window
# https://web.archive.org/web/20130407200745/http://www.divertednetworks.net/apple-captiveportal.html
capnetsupsettings=/Library/Preferences/SystemConfiguration/CaptiveNetworkSupport/Settings.plist
if grep -q -F apple.com $capnetsupsettings; then
    echo Fixing $capnetsupsettings...
    sudo sed -i .orig 's/\.apple\.com/\.localhost/g' $capnetsupsettings
fi

# Last, remove bogus CAs
./macosx_rm_cas.sh

exit 0

###############################################################################
## rest deemed too dangerous for new Mac Pro

if [ -e /Private/var/vm/sleepimage ]; then
    echo "Remove the sleep image file to save disk space"
    sudo rm -f /Private/var/vm/sleepimage
    echo "Creating a zero-byte file instead..."
    sudo touch /Private/var/vm/sleepimage
    echo "...and make sure it cannot be rewritten"
    sudo chflags uchg /Private/var/vm/sleepimage
fi

function xpmset {
    local description="$1"; shift
    local flag="$1"; shift
    local setting="$1"; shift
    local value="$1"

    local current=$(pmset -g | grep " $setting " | awk '{print $2}')
    if [ "$current" != "$value" ]; then
	echo $description
	echo sudo pmset $flag "$setting" "$value"
    fi
}

# speeds up entering sleep mode
xpmset "Disable hibernation" -a hibernatemode 0

model=`ioreg -l |fgrep '"product-name" = <' |cut -d ""="" -f 2|sed -e 's/[^[:alnum:]]//g' | sed 's/[0-9]//g'`

if [ "$model" == "MacBookPro" ]; then
    # so I can wake 
    xpmset "DO wake on magic packet" -a womp 1

    # better have an SSD!!!!
    xpmset "Disable the sudden motion sensor" -a sms 0

    # http://www.cultofmac.com/221392/quick-hack-speeds-up-retina-macbooks-wake-from-sleep-os-x-tips/
    xpmset "Speedup wake from sleep" -a standbydelay 86400
elif [ "$model" == "MacPro" ]; then
    xpmset "Disable computer sleep" -a sleep 0
    xpmset "Set display sleep to 10 minutes" -a displaysleep 10
    xpmset "Set disk sleep to 10 minutes" -a disksleep 10
    xpmset "Set autorestart to off" -a autorestart 0
    xpmset "DO NOT wake on magic packet" -a womp 0
fi

function ethernet_device_name {
    networksetup -listallnetworkservices | grep Ethernet | head -1
}

ethernet="$(ethernet_device_name)"

# This makes wake from sleep work better:
sudo networksetup -setv6LinkLocal "$ethernet" 

exit 0

###############################################################################
##### TODO ####################################################################
###############################################################################

# need to write xnvram function to mirror above ones
xnvram "Disable sound on boot" SystemAudioVolume=" "

# Disable Notification Center and remove the menu bar icon
launchctl unload -w /System/Library/LaunchAgents/com.apple.notificationcenterui.plist 2> /dev/null

# Cannot automate this, since it gets turned back on under various
# conditions.  Also, can query the current value.
# Perhaps run as a root cron job??
echo "Disabling TM local snapshots"
hash tmutil &> /dev/null && sudo tmutil disablelocal
