#! /usr/bin/env bash

set -eu
set -o pipefail

prog="$(basename "$0")"

function errordie {
    [ "${*-}" ] && echo "$prog: $*" 1>&2
    exit 1
}

# Common to both Homebrew and MacPorts
packages="autossh bash coreutils curl diffutils findutils \
       git grep jq moreutils openssh wget"

if [ -x /opt/local/bin/port ]; then
    macports=notnull
    brew=
    manager="sudo /opt/local/bin/port -N"
    packages="$packages fwknop-client gsed gnutar parallel perl5 man"
    if [[ "$(hostname)" =~ mack2 ]]; then
	# shellcheck pulls in a /lot/ of depends
	packages="$packages xmlstarlet shellcheck"
    fi
    update="selfupdate"
    upgrade="upgrade outdated"
    cleanup="uninstall inactive"
elif [ -x /usr/local/bin/brew ]; then
    macports=
    brew=notnull
    if id -Gn $USER | grep -q -w admin; then
	: # OK to install
    else
	errordie "you must be an 'admin' to use Homebrew"
    fi
    if [ $(id -u) -eq 0 ]; then
	manager="sudo --login -u admin /usr/local/bin/brew"
    else
	manager="/usr/local/bin/brew"
    fi
    # 'xmlstarlet' and 'shellcheck' are quick to install in Homebrew
    packages="$packages fwknop gnu-sed gnu-tar perl xmlstarlet shellcheck"
    update="update"
    upgrade="upgrade"
    cleanup="cleanup"
else
    errordie cannot find MacPorts or Homebrew package manager.
fi

###############################################################################

function usage {
    [ "${*-}" ] && echo "$prog: $*" 1>&2
    cat 1>&2 <<EOF
Usage: $prog [--debug] [--help] [--clean]

Install ports/formulae for MacPorts/Homebrew.  The following
packages will be installed:
$(echo $packages | xargs -n 6 echo "  ")

Options:
--debug   :: show what would be done
--clean   :: clean up after installation
EOF
    exit 1
}

debug=
clean=

while [ $# -gt 0 ]; do
    case $1 in
        --help)  usage ;;
        --clean) clean=$1 ;;
        --debug) debug=$1 ;;
        *)       break ;;
    esac
    shift
done

function d {
    if [ "$debug" ]; then
	echo "would: $*"
    else
	echo "+ $*"
        "$@"
    fi
}

# A good time to make sure analytics are turned off
[ "$brew" ] && d $manager analytics off

d $manager $update
d $manager $upgrade
d $manager install $packages

[ "$clean" ] && d $manager $cleanup
