#! /usr/bin/env bash
# print the external IP

set -ueE -o pipefail

prog="$(basename "$0")"

function errordie {
    [ "${*-}" ] && echo "$prog: $*" 1>&2
    exit 1
}

[ $# -gt 0 ] && errordie script takes no arguments

if ! type -p curl > /dev/null; then
    errordie "Cannot find curl, please install it before running $prog"
fi

function get_ip {
    local url=$1
    local ip
    ip=$(curl -4 -s "$url" 2>&1)
    if [[ "$ip" =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ ]]; then
        echo "$ip"
    else
        return 1
    fi
}

if ! ourip=$(get_ip "https://ifconfig.me"); then
    if ! ourip=$(get_ip "https://icanhazip.com"); then
        if ! ourip=$(get_ip "https://ipinfo.io/ip"); then
            if ! ourip=$(get_ip "https://ifconfig.co"); then
                errordie "cannot find our IP!"
            fi
        fi
    fi
fi

echo "$ourip"
