#! /usr/bin/env bash
# examples:
# $ ./onall.sh -d bink -e '(layerpro|gremlin|git)' git pull -r

prog="$(basename "$0")"

usage="[-i] [-e regex] [-d directory] [-u user] command args...

-i :: ignore errors
-e :: except machines by regex argument
-d :: cd to 'directory' first
-u :: execute as 'user'
"

set -ueE -o pipefail

function usage {
    [ "${*-}" ] && echo "$prog: Error: $*" 1>&2
    echo "Usage: $prog: $usage" 1>&2
    exit 1
}

function errordie {
    [ "${*-}" ] && echo "$prog: Error: $*" 1>&2
    exit 1
}

[ "${ONALL_HOSTS-}" ] || errordie ONALL_HOSTS: env var undefined

cd=
ignoreerrors=
except=
user=${USER}

while [ $# -gt 0 ]; do
    case $1 in
        -d|--cd)
	    [ $# -lt 2 ] && usage missing companion arg to --cd
            shift
            cd="cd $1 &&"
            ;;
	-e) except="$2"; shift ;;
	-i) ignoreerrors=$1 ;;
	--user)
	    [ $# -lt 2 ] && usage missing companion arg to --user
	    shift
	    user="$1"
	    ;;
        -*) usage ;;
        *)  break ;;
    esac
    shift
done

hosts=${ONALL_HOSTS}

if [ "$except" ]; then
    tmp=
    for h in $hosts; do
	if [[ $h =~ $except ]]; then
	    echo "Note: skip host $h"
	else
	    tmp="$tmp $h"
	fi
    done
    hosts=$tmp
fi

# from http://stackoverflow.com/questions/6592376/prevent-ssh-from-breaking-up-shell-script-parameters
QUOTE_ARGS=''
for ARG in "$@"; do
    ARG=$(printf "%q" "$ARG")
    QUOTE_ARGS="${QUOTE_ARGS} $ARG"
done

tempfile="/tmp/${prog}temp$$"
rm -f "$tempfile"
function exit_cleanup {
    /bin/rm -f "$tempfile"
}
function err_report {
    echo "Error on line $(caller)" 1>&2
}
trap err_report   ERR
trap exit_cleanup EXIT

{
    for h in $hosts; do
        rm -f "$tempfile"
	if [ "${SSH_IDENT-}" ]; then
	    ssh="ssh -A -i .ssh/${SSH_IDENT}"
	else
	    ssh="ssh -A"
	fi
	if [ "$ignoreerrors" ]; then
	    $ssh "${user}@$h" "$cd${QUOTE_ARGS}" || true &>> "$tempfile"
	else
	    $ssh "${user}@$h" "$cd${QUOTE_ARGS}" &>> "$tempfile"
	fi

        if [ -s "$tempfile" ]; then
	    echo ""
	    echo "============= $h ========================================"
            cat "$tempfile"
        fi
    done
}
