#! /bin/bash

set -eu

if [ $# -ne 1 ]; then
    echo Usage: $0 pidfile
    exit 1
fi

case "$1" in
     /tmp/autosshpid*)
	;;
     *)  echo "$0: illegal argument: $1"
	 exit 1
esac

if [ ! -f $1 ]; then
    echo $0: $1 does not exist
else
    kill $(cat $1)
    rm -f $1
fi
