#! /usr/bin/env bash
#
# This wrapper for SSH allows more flexible configuration.  Specifically:
#  * building the SSH config file (~/.ssh/config) based on location
#    (Yes, SSH version >= 7.3p1 has an Include directive, but some
#     machines I use don't have that version, like CentOS 6 & SunOS.)
#  * providing options based on the version of the client SSH
#
# The main benefit, currently, is providing the option
#   WarnWeakCrypto=no
# for OpenSSH 10.1 and later, because for years I will use it to
# older systems which cannot be updated.
#
# If you want o use the "build config file" features, there are two
# variables which are important:
#   __sshwrap_config_files   :: the array of files which go into creating
#       the main config file, ~/.ssh/config.  List them in order.
#       If this variable is not defined, then no config processing
#       happens.
#   __sshwraprc_force_update :: normally the main config is rebuilt when
#       needed, but this can be set to force a rebuild if, for example,
#       you detect that your IP is now in a different location.
# Next, you need to create  ~/.sshwraprc (see sshwraprc.example).
# Lastly, in some directory in your $PATH, before the real `ssh` appears,
# link to this script with the name `ssh` and `scp`.

set -ueE -o pipefail

prog="$(basename "$0")"

function errordie {
    [ "${*-}" ] && echo "Error: ${prog}: $*" 1>&2
    exit 1
}

if [ "$(uname -s)" = "SunOS" ]; then
    egrep=egrep
else
    egrep="grep -E"
fi

rc="$HOME/.sshwraprc"
if [ -f "$rc" ]; then
    # shellcheck disable=SC1090
    source "$rc"
fi

function executable_p {
    if [ -x "$1" ]; then
	echo "$1"
	return 0
    else
	return 1
    fi
}

# this will be either ssh or scp
app=$(basename "${BASH_SOURCE[0]}")

if realsxx=$(executable_p "/opt/local/bin/${app}"); then
    : # macOS Mac Ports
elif realsxx=$(executable_p "/usr/local/bin/${app}"); then
    : # macOS Homebrew
elif realsxx=$(executable_p "/opt/homebrew/bin/${app}"); then
    : # macOS Homebrew on M1/Big Sur
elif realsxx=$(executable_p "/usr/bin/${app}"); then
    :
elif realsxx=$(executable_p "/bin/${app}"); then
    :
else
    realsxx=
fi

[ "$realsxx" ] || errordie "cannot find ${app} binary"

p="$HOME/.ssh"

ignore=
rebuild=
# shellcheck disable=SC2154
if ! declare -p __sshwrap_config_files &> /dev/null; then
    # Not defined, so don't do any config processing
    ignore=yes
elif [ "${__sshwraprc_force_update-}" ]; then
    rebuild="__sshwraprc_force_update non-null"
elif [ ! -f "$p/config" ]; then
    rebuild="config does not exist"
else
    # shellcheck disable=SC2154
    for config in "$rc" "${__sshwrap_config_files[@]}"; do
        if [ "$config" -nt "$p/config" ]; then
            rebuild="$config newer than $p/config"
            break
        fi
    done
fi

lockfile="/tmp/${prog}.lock"

function exit_cleanup {
    /bin/rm -f "$lockfile"
}
function err_report {
    echo "Error on line $(caller)" 1>&2
}
trap err_report   ERR
trap exit_cleanup EXIT

# thor/thunder don't have lockfile
if ! type -p lockfile &> /dev/null; then
    function lockfile {
        :
    }
fi

if [ ! "$ignore" ] && [ "$rebuild" ]; then
    echo "Updating $p/config: reason: $rebuild" 1>&2

    if [ "$(uname -s)" = "SunOS" ]; then
	cpp=/usr/lib/cpp
    else
	cpp=cpp
    fi
    # lock to update $p/config
    i=0
    while true; do
        if ! lockfile -r 0 "$lockfile"; then
            if [ $i -gt 4 ]; then
                errordie "lockfile $lockfile busy could not update $p/config"
            fi
            i=$(( i + 1 ))
        fi
        # got lock file, get out of here
        break
    done

    echo "   configs: ${__sshwrap_config_files[*]}" 1>&2
    # shellcheck disable=SC2001
    host=$(sed -e 's/\..*$//' <<< "$HOSTNAME")
    cat "${__sshwrap_config_files[@]}" | \
        $egrep -v '^\s*#' | \
        sed -e 's/^!/#/g' | \
        $cpp -undef "-D__host_$host" | \
        $egrep -v '^#' > "$p/config"

    rm -f "$lockfile"
fi

if [[ $($realsxx -V 2>&1) =~ OpenSSH_([0-9]+)\.([0-9]+) ]]; then
    ssh_major_version=${BASH_REMATCH[1]}
    ssh_minor_version=${BASH_REMATCH[2]}
else
    # could not determine, default to "old" (e.g., 1.0 in this case)
    ssh_major_version=1
    ssh_minor_version=0
fi

options="-o AddKeysToAgent=yes"

if (( ssh_major_version < 10 ||
      ( ssh_major_version = 10 && ssh_minor_version < 1 ) ))
then
    : # doesn't have it
else
    options="$options -o WarnWeakCrypto=no"
fi

# shellcheck disable=SC2086
exec $realsxx $options "$@"
