#! /bin/bash
# usage: start_caffeinate_daemon [seconds]
#   prevent the computer from sleeping for the given number of seconds,
#   or 24-hours if no argument is given.

pidfile=xxx
if [ "${1-}" ]; then
    seconds=$1
    # in this case, we don't need the pid file
    pidfile=
else
    # no args, default to 1 hour
    seconds=3600
fi

nohup caffeinate -s -t $seconds \
    > /dev/null 2> /dev/null \
    < /dev/null &
pid=$!
if [ "$pidfile" ]; then
    mkdir -p $HOME/tmp
    echo $pid > $HOME/tmp/caffeinate.pid
fi
